### ISSUE TITLE
draft-ietf-lamps-pkix-shake-02 Identifiers by Jim

### ISSUE THREAD

**Issue by cisco-sro** [csosto-pk/adding-shake-to-pkix#17]
This section needs to nail down all parameters associated w/
the different SHAKE functions when used here.  Otherwise you end up with the
first assumption that I made which was d = 128 for SHAKE128 which would not
produce an acceptable result.

**Comment by cisco-sro** [comment]
By Quynh 

> The specification of output lengths of the 2 SHAKEs is in Sections 4.1.1 and 4.1.2.  Adding a sentence " See Sections 4.1.1 and 4.1.2 for specification of a required output length for each use of SHAKE128 or SHAKE256 in RSASSA-PSS and ECDSA."

**Comment by csosto-pk** [comment]
Fixed 
> Section 5.1.1 and Section 5.1.2 specify the required output length
>  for each use of SHAKE128 or SHAKE256 in RSASSA-PSS and ECDSA.
