### ISSUE TITLE
draft-ietf-lamps-pkix-shake-02 Signatures

### ISSUE THREAD

**Issue by cisco-sro** [csosto-pk/adding-shake-to-pkix#18]
Para #3 - you refer to section 3 for OIDs, but they are not
there for public keys.

**Comment by cisco-sro** [comment]
By Quynh 

> Adding this "
Conforming CA implementations MUST specify the algorithms explicitly
   by using the OIDs specified in Section 3 when encoding  public keys for RSASSA-PSS and ECDSA with SHAKE signatures in certificates and CRLs." as the first paragraph in Section 4.2 "Public keys".

**Comment by csosto-pk** [comment]
Fixed in the Sig section
> Conforming CA implementations MUST specify the algorithms explicitly by using the OIDs specified in Section 4 when encoding RSASSA-PSS and ECDSA with SHAKE signatures in certificates and CRLs.  

And the public keys section 
> Conforming CA implementations MUST specify the algorithms explicitly by using the OIDs specified in Section 4 when encoding RSASSA-PSS and ECDSA with SHAKE public keys in certificates and CRLs.  The
   conventions for RSASSA-PSS and ECDSA public keys algorithm identifiers are as specified in [RFC3279], [RFC4055] and [RFC5480], but we include them below for convenience.
