### ISSUE TITLE
 draft-ietf-lamps-pkix-shake-02 Deterministic ECDSA

### ISSUE THREAD

**Issue by cisco-sro** [csosto-pk/adding-shake-to-pkix#20]
Why is there no reference to deterministic ECDSA signatures in the
document.

**Comment by cisco-sro** [comment]
By Quynh 

> Deterministic ECDSA has a different signing function because of the way k is generated. The working group has not adopted this option yet. Verification is the same.

**Comment by cisco-sro** [comment]
[JLS] If you want to say that it is a different signature algorithm that is fine.  I’ll call and raise.  It should be that it is required that ECDSA w/ SHAKE implements deterministic ECDSA and MUST NOT use a random generator for k.

**Comment by csosto-pk** [comment]
From Russ. H
> I have not heard anyone speak against Jim's suggestion for deterministic ECDSA without a random generator for k. Let's go that way unless there is a scream from the group now.

**Comment by csosto-pk** [comment]
Fixed 
> Conforming CA implementations that generate ECDSA with SHAKE signatures in certificates or CRLs MUST generate such signatures with a deterministicly generated non-random k in accordance with all the requirements specified in [RFC6979].  They MAY also generate such signatures in accordance with all the recommendations in [X9.62] or [SEC1] if they have a stated policy that requires conformance to these standards. ...
