### ISSUE TITLE
draft-ietf-lamps-cms-shakes-01 Identifiers

### ISSUE THREAD

**Issue by cisco-sro** [csosto-pk/adding-shake-to-pkix#23]
Identifiers - The values of d need to be discussed as part of the OID definition.

**Comment by cisco-sro** [comment]
Answer by Quynh 

> " See Section 4.1 for for a required output length when SHAKE128 or SHAKE256 is used to generate a message digest.  

See Sections 4.2.1 and 4.2.2 for specification of a required output length for each use of SHAKE128 or SHAKE256 in RSASSA-PSS and ECDSA." 

Required MAC lengths for KmacWithSHAKE128  and KmacWithSHAKE256 are 256 and 512 bits respectively. See Section 4.4 for a complete specification of KMAC in CMS.

**Comment by cisco-sro** [comment]
[JLS] I want to see the numbers for message digest in this section, not a reference down to some other text.

**Comment by cisco-sro** [comment]
By Quynh 

> I think it is a style issue. If we put the lengths for "message digests" here, then it would not look consistent if not doing the same for the other 2 cases: signatures and KMACs.

> For signatures (RSS-PSS), it requires a section to explain the usages of the SHAKEs: 2 different output lengths at 2 different places. The length when it is used in MGF 1 depends on the modulus size n. So, it is better to refer to the section. 

For KMAC, in its official NIST specification, the output size is called L: it is output size of a KMAC, not strictly of a SHAKE because in a KMAC encoding L is a part of the function's input.  So, KMAC and SHAKE are not the same. 

> However, we could say that Mac lengths of the KMACs are 256 and 512 bits respectively in this specification.  But, doing that would still create an inconsistency issue.  

> Anyway, we could repeat some text from later sections in this "Identifiers" section to provide the lengths that you like. But that would create some text repetitions that you indicated that you did not like to see between the 2 docs.

**Comment by cisco-sro** [comment]
> I think it is a style issue...

[JLS2] The only place for signatures where this is interesting is PSS and that is fixed with a new MGF. 

> For KMAC, in its official NIST ...

[JLS2] I don’t understand what you are saying here.  However I don’t think it matters.  For the KMAC OIDs that are being defined there is a fixed output size and that could be documented here just as easily (or in addition to) putting it in section 4.4.  I want things easy to find, when I find the OID if it tells me the size of the output then that is one place I am looking.  It would also be good to put the expected output lengths in the comments of the ASN.1 module as well.

> Anyway, we could repeat some text...

[JLS2] that comment was really an indicator that it might have been better to have a single document for all of this rather than a complaint about having the information I need where I need it.  I would not expect them to merge at this time.

**Comment by csosto-pk** [comment]
Added text 

> Section 4.1, Section 4.2.1, Section 4.2.2 and Section 4.4 specify the required output length for each use of SHAKE128 or SHAKE256 in  message digests, RSASSA-PSS, ECDSA and KMAC.

I would like to avoid repeating text in multiple places. If the WG insists, we could add the lengths in the OID definition section for both the PKIX and the CMS draft.
