### ISSUE TITLE
draft-ietf-lamps-cms-shakes-01 SHAKE length by Jim

### ISSUE THREAD

**Issue by cisco-sro** [csosto-pk/adding-shake-to-pkix#24]
Is there an issue with SHAKE128 of generating two different lengths from
the same computing instance?  Should be discussed some place.  Note that
putting this in Security Considerations paragraph 2 would be a reasonable
answer in you can tell people WHY they should not expect unrelated outputs.

**Comment by cisco-sro** [comment]
By Quynh 

> It is covered/described in security considerations section.

**Comment by cisco-sro** [comment]
[JLS] I don’t think that it does a good job of covering why the outputs are related when different output lengths are used.  Consider that if SHAKE prefixed the message internally with the length of the output then the outputs would not be related.

**Comment by cisco-sro** [comment]
By Quynh 

>That is a fundamental construction of the sponge construction. I did not want to get into that angle with this document.  

> We could say that: "The shorter one of any 2 outputs produced from a SHAKE with the same input is a prefix of the longer one. It is a similar situation as truncating an 512-bit output of SHA-512 by taking its 256 left-most bits. These 256 left-most bits are a prefix of the 512-bit output. 

> Would you be ok with that ?

**Comment by cisco-sro** [comment]
[JLS2] Yes that is exactly the type of explanation that people are going to understand.

**Comment by csosto-pk** [comment]
Updated security Considerations second paragraph with 

> The SHAKEs are deterministic functions.  Like any other deterministic functions, executing each function with the same input multiple times will produce the same output.  Therefore, users should not expect unrelated outputs (with the same or different output lengths) from excuting a SHAKE function with the same input multiple times.  **The shorter one of any 2 outputs produced from a SHAKE with the same input is a prefix of the longer one.  It is a similar situation as truncating a 512-bit output of SHA-512 by taking its 256 left-most bits.  These 256 left-most bits are a prefix of the 512-bit output.**
