### ISSUE TITLE
draft-ietf-lamps-cms-shakes-01 MAC by Jim

### ISSUE THREAD

**Issue by cisco-sro** [csosto-pk/adding-shake-to-pkix#26]
Do we need to address a potential request
from some of the IOT worlds such as SUIT where they want to use KMAC, but
would be happy with a smaller authentication value?

**Comment by cisco-sro** [comment]
By Quynh 

> Shorter tags are generally ok depending on each application: what are the potential attacks/issues and how much data are MACed under a random key. 

How small would you like for SUIT ? What is the maximum amount of data that will ever be MACed under ONE random key ?

> This is for CMS, I don't think there is a need to reduce the size. But I could be wrong about this.

**Comment by cisco-sro** [comment]
[JLS] One of the message formats that SUIT was using the last time I checked was CMS.  This means that if SUIT wants it then yes it would be for CMS.  Russ – do you think that they are going to want a “truncated” tag for KMAC?

**Comment by cisco-sro** [comment]
By Quynh 

> Yes, I would like to know all about this in SUIT. Generally 128 bits are fine. 96 may be fine depending on the application.

**Comment by cisco-sro** [comment]
By Russ H.

> SUIT will focus on COSE structures, but the charter allows a rfc4108bis.

> So far, size in SUIT has not been a sticking point.  When the signature value or authentication tag is compared to a software image, a few extra octets is not a show stopper.

**Comment by csosto-pk** [comment]
From IETF-103
>We could make it possible to truncate KMAC to less than 256-bites. by making it configurable in the ASN.1.
> But we should use full length KMACs, as Russ suggested.

**Comment by csosto-pk** [comment]
Nothing to change in the draft as we are currently only using full length KMAC.
