### ISSUE TITLE
draft-ietf-lamps-cms-shakes-01 Deterministic ECDSA by Russ H. 

### ISSUE THREAD

**Issue by cisco-sro** [csosto-pk/adding-shake-to-pkix#27]
> I have not heard anyone speak against Jim's suggestion for deterministic ECDSA without a random generator for k.  Let's go that way unless there is a scream from the group now.

**Comment by csosto-pk** [comment]
Fixed 

> Conforming implementations that generate ECDSA with SHAKE signatures in CMS MUST generate such signatures with a deterministicly generated, non-random k in accordance with all the requirements specified in [RFC6979].  They MAY also generate such signatures in accordance with all the recommendations in [X9.62] or [SEC1] if they have a stated policy that requires conformance to these standards.
