### ISSUE TITLE
Sec considerations (by Yoav from IESG Review)

### ISSUE THREAD

**Issue by csosto-pk** [csosto-pk/adding-shake-to-pkix#42]
> In the Security considerations 
> The second paragraph has a SHOULD-level requirement to choose an ECDSA curve with an appropriate strength to match that of the hash function (SHAKE128 vs SHAKE256). This seems to me like a compliance requirement. While this is not a hard-and-fast rule, these should usually go in the body of the document, such as in section 5 rather than in security considerations.  It's also puzzling why there are no similar recommendations for the strength of the RSA key.
> 
> The first paragraph I find confusing.  It states that the SHAKE functions are deterministic, and goes on to explain that this means that executing them on the same input will result in the same output, and that users should not expect this to be the case. Why does this need to be said? Is this not the same for any hash function? The paragraph than goes on to tell the reader that  with different output lengths, the shorter ones are prefixes of the longer ones, and that this is like hash function truncation.  Why do we need any of this information and why is this related to security?  This is especially puzzling considering that the document fixes the output length to a specific value for each of the two functions.

**Comment by csosto-pk** [comment]
Yoav wrote 

> > The second paragraph has a SHOULD-level requirement to choose an ECDSA curve with an appropriate strength to match that of the hash function (SHAKE128 vs SHAKE256). This seems to me like a compliance requirement. While this is not a hard-and-fast rule, these should usually go in the body of the document, such as in section 5 rather than in security considerations.  It's also puzzling why there are no similar recommendations for the strength of the RSA key. 

I moved this paragraph in Section 5.1. It now reads 
> When using RSASSA-PSS or ECDSA with SHAKEs, the RSA modulus and ECDSA curve order SHOULD be chosen in line with the SHAKE output length. In the context of this document SHAKE128 OIDs are RECOMMENDED for 2048 or 3072-bit RSA modulus or curves with group order of 256-bits. SHAKE256 OIDs are RECOMMENDED for 4096-bit RSA modulus and higher or curves with group order of 384-bits and higher.

Yoav wrote 
> > The first paragraph I find confusing.  It states that the SHAKE functions are deterministic, and goes on to explain that this means that executing them on the same input will result in the same output, and that users should not expect this to be the case. Why does this need to be said? Is this not the same for any hash function? The paragraph than goes on to tell the reader that  with different output lengths, the shorter ones are prefixes of the longer ones, and that this is like hash function truncation.  Why do we need any of this information and why is this related to security?  This is especially puzzling considering that the document fixes the output length to a specific value for each of the two functions.

The Sec Considerations section now reads 
> This document updates [RFC3279]. The security considerations section of that document applies to this specification as well.
>
> NIST has defined appropriate use of the hash functions in terms of the algorithm strengths and expected time frames for secure use in Special Publications (SPs) [SP800-78-4] and [SP800-107]. These documents can be used as guides to choose appropriate key sizes for various security scenarios.

**Comment by yoavnir** [comment]
Thanks.  This addresses my concerns.
